### ISSUE TITLE
get rid of webapp

### ISSUE THREAD

**Issue by dmd** [dmd/mictools#1]
The webapp sge interface was an awful idea. Just use ssh instead.

```
-v /home/pipeline/.ssh:/pipeline.ssh

ssh -i /pipeline.ssh/id_ecdsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no pipeline@micc command
```

**Comment by dmd** [comment]
Use paramiko or fabric?

**Comment by bbfrederick** [comment]
I’m not familiar with either so I can’t offer any coherent advice. Paramiko is a cooler name.

**Comment by dmd** [comment]
Jordan and Rupa both agree that for a simple case like this, just `subprocess.call` it and don't add yet another library.
